version: '3.1'

services:
  wordpress:
    build: .
    links:
    - db:mysql
    ports:
      - 8080:80
    volumes:
      - /var/www/html
      - ./woocommerce-begateway:/var/www/html/wp-content/plugins/woocommerce-begateway
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
